import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

/**
 * Wiki content collection.
 *
 * Articles live at src/content/<locale>/<contentType>/<slug>.mdx
 * The `id` generated by the glob loader is the path relative to base, without extension,
 * e.g. "en/bosses/gelum".
 *
 * Frontmatter is validated at build time by the Zod schema below. A missing or
 * malformed field fails the build immediately — this is the core advantage over
 * the legacy `export const metadata = {}` approach.
 */
const wiki = defineCollection({
  loader: glob({ pattern: '**/*.mdx', base: './src/content/wiki' }),
  schema: z.object({
    title: z.string().max(80),
    description: z.string().min(40).max(165),
    category: z.string(),
    date: z.coerce.date(),
    lastModified: z.coerce.date().optional(),
    image: z.string().optional(),
    tags: z.array(z.string()).default([]),
    noindex: z.boolean().default(false),
  }),
});

export const collections = { wiki };
